### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by farvardin** [farvardin/lionwiki-t2t#2]
- [x] déplacer dépôt principal de sourceforge vers github
- [x] créer un dépôt pour les templates et alléger le code principal de lionwiki en retirant 90% des templates et polices obsolètes
- [ ] Créer un dépôt pour certains ajouts (abc2js par exemple)
- [ ] version statique : permettre de tout configurer depuis un seul dossier
- [x] version statique : rajouter extension .t2t en plus de .txt et .gmi
- [ ] version statique : rajouter nom global pour le site en entête
- [ ] PHP8 : fix problème écran blanc après édition : lié à inlineDiff/renderer.php
- [ ] jquery & markitup: mise à jour vers version plus récente, si possible (probablement difficile, la version officielle du site utilise une version très obsolète : https://markitup.jaysalvat.com/_scripts/jquery.pack.js)
